# application-dev.properties

# Database — Dev Services auto-starts Postgres container
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.reuse=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.init-script-path=db/init-dev.sql

# Hibernate
quarkus.hibernate-orm.database.default-schema=auth
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=db/dev-seeds.sql
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
